In [1]:
# Q1. Write a code to combine a one a two diamesional NumPy Array
import numpy as np
arr1=np.arange(5)
print("One dimensional array :")
print(arr1)

arr2=np.arange(10).reshape(2,5)
print("\n Two Dimensional array:")
print(arr2)

for a,b in np.nditer ([arr1, arr2]) :
    print("%d : %d "  %(a,b) , )

One dimensional array :
[0 1 2 3 4]

 Two Dimensional array:
[[0 1 2 3 4]
 [5 6 7 8 9]]
0 : 0 
1 : 1 
2 : 2 
3 : 3 
4 : 4 
0 : 5 
1 : 6 
2 : 7 
3 : 8 
4 : 9 


In [2]:
# Q2 Write a code to check  whether a NumPy array contain a spacified row 

import numpy as np
arr=np.array([[2, 3, 0],
             [4, 1, 6]])
print("Given Array:")
print(arr)
print(2 in arr)
print(0  in arr)
print(6 in arr)
print(40  in arr)

Given Array:
[[2 3 0]
 [4 1 6]]
True
True
True
False


In [4]:
# Q3 Write a Pandas code to createb and display a DataFrame form a spacified dictionary data which has the index lables
import pandas as pd
import numpy as np
exam_data={"Name": ["Sagar", "Ajay", "Ram", "sonu", "Rohan","kevin","Rahul","salim","vidhya", "ravin"],
           "Score": [20.5,9,16.5,np.nan,9,20,14.5, np.nan,18,19],
           "Attempts": [1,3,2,3,2,2,1,1,2,1],
           "Quality": ['Yes','no','yes','no','no','yes','yes','no','yes','yes']}

lables=['a','b','c','d','e','f','g','h','i','j']
df=pd.DataFrame(exam_data , index=lables)
print(df)
          

     Name  Score  Attempts Quality
a   Sagar   20.5         1     Yes
b    Ajay    9.0         3      no
c     Ram   16.5         2     yes
d    sonu    NaN         3      no
e   Rohan    9.0         2      no
f   kevin   20.0         2     yes
g   Rahul   14.5         1     yes
h   salim    NaN         1      no
i  vidhya   18.0         2     yes
j   ravin   19.0         1     yes


In [5]:
# Q4 Writr a pandas code to create DataFRame form dict/lists
import pandas as pd
data={'Category' : ['Array', 'stack','Queue'],
     'Marks' : [20,21,19]
     }
df=pd.DataFrame(data)
print(df)

  Category  Marks
0    Array     20
1    stack     21
2    Queue     19


In [6]:
# Q5 Write a pandas code to create pandas dataframe using list of lists
import pandas as pd
data=[ ['Geeks',10], ['For',15]]
df=pd.DataFrame(data, columns=['Name','Age'])
print(df)

    Name  Age
0  Geeks   10
1    For   15
